name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Python
      run: |
        sudo apt update
        sudo apt install python3 python3-pip
    - name: Debug workspace contents
      run: |
        pwd
        ls -R ${{ github.workspace }}
        ls
        ls ../
    - name: Display directory structure
      run: |
        sudo apt update
        sudo apt install tree
        tree /home/runner/work/
        

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        requirements.txt

    - name: Run tests
      run: pytest
