name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Python
      run: |
        sudo apt update
        sudo apt install python3 python3-pip       

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install and Run linters <flake8>
      run: |
        pip install flake8
        flake8 . --count --show-source --statistics --exit-zero

    - name: Install and Run code formatter <black>
      run: |
        pip install black
        black --check .
        black .
        
    - name: Run tests
      run: pytest

    - name: Install Docker
      run: |
          sudo apt remove containerd
          sudo apt install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl restart docker

    - name: Build Docker image from existing Dockerfile
      run: |
          docker build -t flask-app .

    
