name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      run: |
        sudo apt update
        sudo apt install python3 python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r /home/runner/work/flaskr-siemens-project/requirements.txt

    - name: Run tests
      run: pytest
